### ISSUE TITLE
Not adding battle pets value

### ISSUE THREAD

**Issue by Scoboose** [clocklear/BagAppraiser#10]
**Describe the bug**
Bag Appraiser is not adding caged battle pets to the value of items in bags or banks.

**Expected behavior**
Add pets value

**Screenshots**
https://i.imgur.com/dywzeSw.jpeg

**Comment by clocklear** [comment]
Confirmed this is an issue.  Need to find myself a caged battlepet and figure out how to fix the issue.

**Comment by clocklear** [comment]
Fixed in #13 (v9.1.0-2)

**Comment by Scoboose** [comment]
Thank you.
