### ISSUE TITLE
Default Profile

### ISSUE THREAD

**Issue by Plusader** [clocklear/BagAppraiser#12]
**Is your feature request related to a problem? Please describe.**
Everytime you get in contact with a new character unknown to the addon, be it 
- after a fresh/new installation of the addon 
- or after creating a new char
you have to set up the profile to a common one.

**Describe the solution you'd like**
Set the default profile to "Default" and not to the character-specific one.

**Additional context**
I have installed the addon again, after searching for it for a while. Since I have a lot of chars on various account such an improvement would make setting all of them way easier. Think about profiles here from the bottom up. Do they really need to exist? I'd remove them completely and have just one global profile.

**Comment by clocklear** [comment]
I'm curious to know what settings you'd like to be maintained globally.  Are you saying you want to see item values across all characters? (so character A's results on character B?). Or are you saying you want to have the same blocklist maintained globally across all characters?

**Comment by Plusader** [comment]
We have 4 Tabs(General, Filters, About, Profile) currently.

If a new character is registered by the addon, the Profile-Tab shows up with a newly created profile-entry of the new character in the form "Charactername-Realmname".
I think that should be changed, so that a new character has the option "Default" chosen/preset in the profile-tab.
This way already existing changes to the "Default"-profile are active instantly.
This would also prevent a bloating of the already existing profile-list.

**Comment by clocklear** [comment]
I see what you are saying, I think.  You're saying you just want the default to be the 'Default' profile, and then folks can opt into per-user settings as necessary?

**Comment by Plusader** [comment]
Yes, that's it. 
I think that this would make much more sense as a default behaviour.

I would even go so far and delete the profile tab at all, keeping it clean with General, Filters and About.

**Comment by clocklear** [comment]
I agree that the 'Default' profile probably makes sense as a start for most users. I disagree that the notion of profiles is useless, as some users like the capability to have different settings for different characters (myself included). 

I'll work on this as I have time.

**Comment by clocklear** [comment]
Fixed in #13 (v9.1.0-2)
