### ISSUE TITLE
BagAppraiser/core.lua:311: attempt to compare nil with number

### ISSUE THREAD

**Issue by Quartzfire** [clocklear/BagAppraiser#20]
**Describe the bug**
Getting LUA since upgrading to the latest version.

**To Reproduce**
LUA is seen during character login.

**Additional context**
15x BagAppraiser/core.lua:311: attempt to compare nil with number
[string "@BagAppraiser/core.lua"]:311: in function `handleItemValuation'
[string "@BagAppraiser/core.lua"]:271: in function `ValuateBag'
[string "@BagAppraiser/core.lua"]:106: in function `UpdateData'
[string "@BagAppraiser/core.lua"]:227: in function <BagAppraiser/core.lua:226>
[string "=[C]"]: ?
[string "@Accountant/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Accountant/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by clocklear** [comment]
Fixed in #21
