### ISSUE TITLE
ElvUI DataText not available

### ISSUE THREAD

**Issue by wdeasley** [clocklear/BagAppraiser#22]
**Describe the bug**
After recent updates I am no longer able to see the option for BagAppraiser in the EvlUI data Text options

**To Reproduce**
Get Latest ElvUI

**Expected behavior**
Should Be able to select and see BagAppraiser

**Comment by clocklear** [comment]
Sorry for the delay. I had this problem as well. I had to go reconfigure my ElvUI datapanel settings; something within Elv has changed the way Databroker items are named. 

Give that a try and see if it works for you.

**Comment by wdeasley** [comment]
Ok, I see what the issue, is they moved it to LDB: BagAppraiser.  This is the reason that I couldn't find it.  Thank you for the response.
