### ISSUE TITLE
Item filter White list instead of Blacklist and on screen display

### ISSUE THREAD

**Issue by Moregaze** [clocklear/BagAppraiser#23]
No problems.  I would just like to have an item filter white list instead of a blacklist.  Mostly so I can add only things I want to sell like gathered materials.  Instead of having to add everything else in the game to a blacklist that regularly sits in my inventory like consumables.  

Also, an easily movable, and resizable on-screen display of the value of the items tracked would be welcome as with so many map mini-buttons I have to use an addon that combines them into one.  Would just make a play session easier to hit a goal and stop.

**Comment by clocklear** [comment]
Sorry for the delay, these alerts get lost in the sea of alerts from my job.  Interesting idea about the whitelist; should be doable I think.

The latter request is a bit more involved.  It's straight-forward, but will take a bit more work on my part.

**Comment by clocklear** [comment]
The allowlist functionality has been added to v10.0.7-1.  I don't think I'm going to go after the OSD.  Feel free to submit a PR if you want to take a crack at it.
