### ISSUE TITLE
Omitting silver and copper display on LDB button

### ISSUE THREAD

**Issue by tflo** [clocklear/BagAppraiser#24]
Is there any way to get rid of the silver and copper amounts on the LDB button?

If not, then please take it as a suggestion. The silver and copper display eats at least 50px of precious LDB space, and I can't think of a reason why I would be interested in such a degree of ultra-precision.

Also in the tooltip I would prefer to have only gold values, but this is a cosmetic issue, as it isn't wasting space there.

Thanks for considering, or for a hint, in case the option is already there and I'm just blind (as so often),
and thanks for the addon, of course! 

– Tom

**Comment by clocklear** [comment]
Thanks for reaching out! I'm not currently playing WoW, so I'm not currently working on this addon.  I'll take a stab at this whenever I make it back though (plan to come back for 10.1).

**Comment by tflo** [comment]
Never mind, currently I don't use the addon. Thanks for your reply anyway.

I leave the issue open, since you have announced that you will look into it. But feel free to close, if you personally are not interested in the suggestion.

**Comment by clocklear** [comment]
Fixed in version 10.0.7-1 (will release this weekend at some point).

![image](https://user-images.githubusercontent.com/622205/235280768-273a83d2-933c-41ab-ad7b-8dee7ffe9b10.png)
