### ISSUE TITLE
Guild bank value not seen on alts in the same guild

### ISSUE THREAD

**Issue by tflo** [clocklear/BagAppraiser#25]
I opened the guild bank on char A, guild bank value appeared correctly in the tooltip.

Switched to char B then, which is in the same guild. The existing guild bank value is not recognized on that char. (To get the value, I had to visit the guild bank again on that char.)

Repeated on char C (also same guild), but no value there either.

Expected behavior: Guild bank value should be seen on alts in the same guild, as it is not char-specific.

**Comment by clocklear** [comment]
Unfortunately this isn't the way the feature is designed.  It was never intended to allow for sharing of guild bank data between characters of the same guild.  Happy to accept a PR though if you want to take a stab at enabling that functionality.

**Comment by tflo** [comment]
Never mind, currently I don't use the addon. Thanks for your reply anyway.

Should have closed the issue earlier, sorry.
