### ISSUE TITLE
Add more pricing sources

### ISSUE THREAD

**Issue by Goss444** [clocklear/BagAppraiser#31]
The undermine journal is not being updated anymore. Would it be possible to add another source for price? Auctionator? Oribos Exchange?

Thank you.

**Comment by clocklear** [comment]
I'll take a look!

**Comment by clocklear** [comment]
Adding Oribos Exchange support looks relatively straightforward.  I'll work on this tonight.

**Comment by clocklear** [comment]
adding this for my own notes: https://support.tradeskillmaster.com/en_US/custom-strings/which-external-sources-are-available-to-use
