### ISSUE TITLE
frFR  Bug

### ISSUE THREAD

**Issue by Brainc3ll** [clocklear/BagAppraiser#40]
**Describe the bug**

Hello,

Top contributor doesn't show in french,   when i switch to english, everything is fine.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by clocklear** [comment]
Hello!  Thanks for your bug report.  Can you be more specific?  Does the label not display, or the entire feature is missing when in French?

**Comment by Brainc3ll** [comment]
Hello,

Here some screen, with frFR and without frFR

Top contrib setting enabled

Addons used in this screen :  Chocolatebar / Auctionator and BagAppraiser

![with frFR](https://github.com/clocklear/BagAppraiser/assets/70319117/c8492769-00d4-4246-95b5-3476fa4de05f)
![without frFR](https://github.com/clocklear/BagAppraiser/assets/70319117/8c5fbb9b-d662-46b5-afa8-03ff35dde5d7)

**Comment by clocklear** [comment]
Thanks for the screenshots!  Found the problem and fixed it; update will be released later today.

![image](https://github.com/clocklear/BagAppraiser/assets/622205/14d7b35e-d9f7-4613-9b71-2c74bde54d07)

**Comment by Brainc3ll** [comment]
Many thanks, have a great day.
