### ISSUE TITLE
Addon Update Needed

### ISSUE THREAD

**Issue by DeanHollstrom** [clocklear/BagAppraiser#42]
**Describe the bug**

Getting the following error when loading into WoW:

Message: Interface/AddOns/BagAppraiser/const.lua:12: attempt to call local 'GetAddOnMetadata' (a nil value)
Time: Sun Aug 18 16:26:20 2024
Count: 1
Stack: Interface/AddOns/BagAppraiser/const.lua:12: attempt to call local 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/BagAppraiser/const.lua"]:12: in main chunk

Locals: Addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BagAppraiser"
 orderedModules = <table> {
 }
 enabledState = true
 CONST = <table> {
 }
 defaultModuleState = true
}
ADDON_NAME = "BagAppraiser"
L = <table> {
 price_source_desc = "Predefined price sources for item value calculation."
 disabled = "disabled"
 item_added_blocklist = "Added %s to the blocklist."
 quality_filter_toggled = "Quality filter %s"
 open_options = "Left-Click to open the options window"
 rare = "Rare"
 tooltip_money_format_desc = "Controls the precision of the amounts shown in the tooltip."
 region_historical_price = "Region Historical Price"
 price_source_changed = "Price source changed to: "
 recent = "3-Day Price"
 item_on_allowlist = "%s is already on the allowlist."
 enable_guild_bank = "Enable guild bank"
 enabled = "enabled"
 ahdb = "Auction House Database"
 common = "Common"
 min_buyout = "Minimum Buyout"
 region_price = "Region Price"
 feedback = "Feedback"
 combinedtotal = "Combined Total"
 quality_filter_desc = "Items below the selected quality will not factor into calculations"
 stddev = "14-Day Std Dev"
 epic = "Epic"
 atr = "Auctionator"
 feature_allowlist = "NEW -- BagAppraiser now supports allowlists!  Check the config window for more details."
 based_on = "Based on"
 market = "14-Day Price"
 about = "About"
 bags = "Bags"
 region_market_value_avg = "Region Market Value Avg"
 item_on_blocklist = "%s is already on the blocklist."
 text_display = "Text Display"
 item_allowlist_nothing_detected = "No item detected, so nothing added to the allowlist."
 quality_filter_changed = "Quality Filter set to: %s and above"
 poor = "Poor"
 guild_bank_last_updated = "Guild bank last updated"
 author = "Written by clocklear (github.com/clocklear)"
 tsm = "TradeSkillMaster"
 bank_last_updated = "Bank last updated"
 total = "Total"
 item_allowlist_desc = "If enabled, only items added to the allowlist will be counted.  Mutually exclusive with blocklist."
 disabled_instructions = "BagAppraiser is running in disabled mode because a suitable pricing source cannot be found.  You can fix this by installing one of the following addons:"
 bank = "Bank"
 ldb_money_format = "LDB Money Format"
 bag = "Bag"
 item_blocklist_toggled = "Item blocklist %s"
 feature_pricing_sources = "NEW -- In addition to TSM, BagAppraiser now supports Auction House DataBase, Auctionator, and Oribos Exchange as alternative price sources."
 price_source = "Price Source"
 historical_price = "Historical Price"
 item_allowlist_toggled = "Item allowlist %s"
 auction_value = "Auction Value"
 issue_tracker = "Issue Tracker:"
 show_minimap_icon = "Show minimap icon"
 recent_value = "Recent Market Value"
 globalMean = "Regional Mean"
 blocklist_removed_item = "Removed %s from blocklist."
 market_value = "Market Value"
 need_help = "Need help?  Have a feature request?  Open an issue on the code repository for BagAppraiser or send me a PM on Reddit."
 show_top_contributors = "Show top contributors"
 enable_guild_bank_desc = "Summarize the contents of the guild bank.  This settings has no effect if you aren't in a guild."
 realm_price = "Realm Price"
 enable_quality_filter = "Enable quality filter"
 credits = "Credits"
 vendorsell = "VendorSell"
 item_blocklist_nothing_detected = "No item detected, so nothing added to the blocklist."
 woweconomy_thanks = "Thanks to /r/woweconomy for the support and the great feature ideas."
 ldb_label_source_desc = "Controls what is displayed for the addon within LDB host frames."
 price_source_poor = "Poor quality items are always valued with the VendorSell source."
 item_blocklist_desc = "If enabled,

**Comment by clocklear** [comment]
It looks like Blizz moved `GetAddonMetadata` to `C_Addons.GetAddonMetadata`.  I hope to take a stab at getting this working with TWW tonight/tomorrow and have an update ready soon(-ish).

**Comment by clocklear** [comment]
@DeanHollstrom Should be fixed in v11.0.2-1.  Warbands bank is not scanned yet; I'll figure out to scan that later.
