### ISSUE TITLE
Option to track reagent bag only

### ISSUE THREAD

**Issue by Sneed-Daytona** [clocklear/BagAppraiser#43]
Any way you could add this? I like to use your addon for gathering only really and have to finagle white/block lists when it could just track the reagent bag.

Ty for your time

**Comment by clocklear** [comment]
That's a really good idea! Lemme see what I can do. 👍

**Comment by clocklear** [comment]
Added basic support in #44 .  This is released as `v11.0.2-3`; you can find the new bag selection filter in the 'Filter' options.

Let me know if you encounter any issues; I didn't test it _super_ thoroughly.

**Comment by Sneed-Daytona** [comment]
Alright I have it installed and it is working. Also prices changes with each selection in titanpanel as well. I will keep an eye on it and report any errors.
