### ISSUE TITLE
Allowed white list

### ISSUE THREAD

**Issue by FCPerfectO** [clocklear/BagAppraiser#45]
hello. can you help me plz. how to add items to addon BagAppraiser, filter, allowed list? I can't open my bag when this menu is opened

**Comment by clocklear** [comment]
Hey there!  Sorry for the delay; there must be some other addon that is preventing you opening your bags and the addon options at the same time; I haven't added any functionality to prevent that being the case.

When you do get them open together, you drag from your bag to the drop zone in options and the item will be added to the appropriate list.

**Comment by FCPerfectO** [comment]
![1](https://github.com/user-attachments/assets/c47e7c95-1316-4d5f-94ca-ce4fd3d01075)
As you can see when addon tab is opened, I can't open bags. what am I doing wrong?

**Comment by clocklear** [comment]
Perhaps this is a WoW UI limitation on smaller screens?  I'm using the addon with ElvUI and it works.  I'll try later tonight with the base UI as it seems that's what you are using, but you should definitely be able to option the options screen and your bag at the same time.

**Comment by FCPerfectO** [comment]
Try it with default UI, please. I don't use any addon or bag addon. some other addons have their own addon window and bag can be opened. but your addon use only system UI addon page and bags are locked there.

**Comment by clocklear** [comment]
Can confirm; the default UI no longer allows you to have your bags and the main menu open at the same time. 😞   This used to work; apparently Blizzard changed something along the way.

I'm still testing to find a workaround but I don't have any immediate suggestions.  I can't seem to find a way to disable this behavior.

**Comment by clocklear** [comment]
![image](https://github.com/user-attachments/assets/ce2f7a3b-1962-4a57-8e8b-4f3cad1e15b4)

It's not ideal, but if you install any of the bag replacement addons, you should be able to open both at the same time.  For instance, here's [BetterBags](https://www.curseforge.com/wow/addons/better-bags) open alongside the BagAppraiser options menu.  Worst case: you can use this to set your allow/disallow lists appropriately, then disable the bag addon.

**Comment by FCPerfectO** [comment]
Yes, you are right. I used Baganator addon and it works too.
